[package]
name = "leetcode"
version = "0.1.0"
authors = ["Joaq33 <joakoillia@gmail.com>"]
edition = "2018"

[[bin]]
name = "132_pattern"
path = "uncompleted/132_pattern.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
